import eventsData from "../data/events.json" with { type: "json" };
import sourcesData from "../data/sources.json" with { type: "json" };
import voicesData from "../data/voices.json" with { type: "json" };
import indicatorsData from "../data/indicators.json" with { type: "json" };
export const events = Array.isArray(eventsData) ? eventsData : Object.values(eventsData);
export const sources = Array.isArray(sourcesData) ? sourcesData : Object.entries(sourcesData).map(([id, source]) => ({ id, ...source }));
export const voices = Array.isArray(voicesData) ? voicesData : Object.values(voicesData);
export const indicators = Array.isArray(indicatorsData) ? indicatorsData : Object.values(indicatorsData);
export const getEvent = (id) => events.find((event) => event.id === id);
export const getSource = (id) => sources.find((source) => source.id === id);
export const eventSources = (event) => (event.sources || []).map(getSource).filter(Boolean);
export const activeEvents = () => events;
