const { Client } = require('pg');

async function run() {
  const client = new Client({
    connectionString: 'postgresql://postgres.pjonynkzgsfwojwboixi:OJb7DMWgEFcBAr7h@aws-0-ap-northeast-1.pooler.supabase.com:6543/postgres',
    ssl: { rejectUnauthorized: false }
  });
  
  try {
    await client.connect();
    console.log('Connected to Supabase PostgreSQL in ap-northeast-1!');
    
    // Apply RLS fix and grant access to anon role
    const sql = `
      -- Ensure the table exists
      CREATE TABLE IF NOT EXISTS letsfixindia_submissions (
          id bigint generated by default as identity primary key,
          data jsonb not null,
          created_at timestamp with time zone default timezone('utc'::text, now()) not null
      );

      -- Grant permissions to the anon, authenticated, and service_role roles
      GRANT ALL ON letsfixindia_submissions TO anon;
      GRANT ALL ON letsfixindia_submissions TO authenticated;
      GRANT ALL ON letsfixindia_submissions TO service_role;
      GRANT USAGE, SELECT ON SEQUENCE letsfixindia_submissions_id_seq TO anon;
      GRANT USAGE, SELECT ON SEQUENCE letsfixindia_submissions_id_seq TO authenticated;

      -- Enable RLS and create policy for public inserts
      ALTER TABLE letsfixindia_submissions ENABLE ROW LEVEL SECURITY;
      
      DROP POLICY IF EXISTS "Allow public inserts" ON letsfixindia_submissions;
      DROP POLICY IF EXISTS "anon insert" ON letsfixindia_submissions;
      DROP POLICY IF EXISTS "Enable insert for all users" ON letsfixindia_submissions;
      
      CREATE POLICY "Enable insert for all users" ON letsfixindia_submissions 
          AS PERMISSIVE FOR INSERT TO anon WITH CHECK (true);
          
      -- Also add a policy for SELECT so we can read it to verify
      DROP POLICY IF EXISTS "Allow public select" ON letsfixindia_submissions;
      CREATE POLICY "Allow public select" ON letsfixindia_submissions 
          AS PERMISSIVE FOR SELECT TO anon USING (true);
    `;
    
    await client.query(sql);
    console.log('Applied SQL commands to configure letsfixindia_submissions successfully.');
    
  } catch (err) {
    console.error('Error applying configuration:', err);
  } finally {
    await client.end();
  }
}

run();
