-- Create the submissions table
CREATE TABLE IF NOT EXISTS letsfixindia_submissions (
    id bigint generated by default as identity primary key,
    data jsonb not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
ALTER TABLE letsfixindia_submissions ENABLE ROW LEVEL SECURITY;

-- Create policy to allow anonymous inserts (submissions from the public web form)
CREATE POLICY "Allow public inserts" ON letsfixindia_submissions
    FOR INSERT
    TO public
    WITH CHECK (true);
